// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MESSAGES_EVE_LOCALIZATION_H_
#define FLATBUFFERS_GENERATED_MESSAGES_EVE_LOCALIZATION_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace eve {
namespace localization {

struct Metadata;
struct MetadataBuilder;

struct KwargNumber;
struct KwargNumberBuilder;

struct KwargString;
struct KwargStringBuilder;

struct Kwarg;
struct KwargBuilder;

struct Token;
struct TokenBuilder;

struct Message;
struct MessageBuilder;

struct AllMessages;
struct AllMessagesBuilder;

enum KwargValue : uint8_t {
  KwargValue_NONE = 0,
  KwargValue_KwargNumber = 1,
  KwargValue_KwargString = 2,
  KwargValue_MIN = KwargValue_NONE,
  KwargValue_MAX = KwargValue_KwargString
};

inline const KwargValue (&EnumValuesKwargValue())[3] {
  static const KwargValue values[] = {
    KwargValue_NONE,
    KwargValue_KwargNumber,
    KwargValue_KwargString
  };
  return values;
}

inline const char * const *EnumNamesKwargValue() {
  static const char * const names[4] = {
    "NONE",
    "KwargNumber",
    "KwargString",
    nullptr
  };
  return names;
}

inline const char *EnumNameKwargValue(KwargValue e) {
  if (::flatbuffers::IsOutRange(e, KwargValue_NONE, KwargValue_KwargString)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesKwargValue()[index];
}

template<typename T> struct KwargValueTraits {
  static const KwargValue enum_value = KwargValue_NONE;
};

template<> struct KwargValueTraits<eve::localization::KwargNumber> {
  static const KwargValue enum_value = KwargValue_KwargNumber;
};

template<> struct KwargValueTraits<eve::localization::KwargString> {
  static const KwargValue enum_value = KwargValue_KwargString;
};

bool VerifyKwargValue(::flatbuffers::Verifier &verifier, const void *obj, KwargValue type);
bool VerifyKwargValueVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

enum VariableTypes : int8_t {
  VariableTypes_character = 0,
  VariableTypes_npcOrganization = 1,
  VariableTypes_item = 2,
  VariableTypes_location = 3,
  VariableTypes_characterlist = 4,
  VariableTypes_messageid = 5,
  VariableTypes_datetime = 6,
  VariableTypes_formattedtime = 7,
  VariableTypes_timeinterval = 8,
  VariableTypes_numeric = 9,
  VariableTypes_generic = 10,
  VariableTypes_MIN = VariableTypes_character,
  VariableTypes_MAX = VariableTypes_generic
};

inline const VariableTypes (&EnumValuesVariableTypes())[11] {
  static const VariableTypes values[] = {
    VariableTypes_character,
    VariableTypes_npcOrganization,
    VariableTypes_item,
    VariableTypes_location,
    VariableTypes_characterlist,
    VariableTypes_messageid,
    VariableTypes_datetime,
    VariableTypes_formattedtime,
    VariableTypes_timeinterval,
    VariableTypes_numeric,
    VariableTypes_generic
  };
  return values;
}

inline const char * const *EnumNamesVariableTypes() {
  static const char * const names[12] = {
    "character",
    "npcOrganization",
    "item",
    "location",
    "characterlist",
    "messageid",
    "datetime",
    "formattedtime",
    "timeinterval",
    "numeric",
    "generic",
    nullptr
  };
  return names;
}

inline const char *EnumNameVariableTypes(VariableTypes e) {
  if (::flatbuffers::IsOutRange(e, VariableTypes_character, VariableTypes_generic)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesVariableTypes()[index];
}

enum ArgFlag : uint16_t {
  ArgFlag_linkify = 1,
  ArgFlag_capitalize = 2,
  ArgFlag_uppercase = 4,
  ArgFlag_lowercase = 8,
  ArgFlag_titlecase = 16,
  ArgFlag_useGrouping = 32,
  ArgFlag_conditional = 64,
  ArgFlag_quantity = 256,
  ArgFlag_decimalPlaces = 512,
  ArgFlag_leadingZeroes = 1024,
  ArgFlag_MIN = ArgFlag_linkify,
  ArgFlag_MAX = ArgFlag_leadingZeroes
};

inline const ArgFlag (&EnumValuesArgFlag())[10] {
  static const ArgFlag values[] = {
    ArgFlag_linkify,
    ArgFlag_capitalize,
    ArgFlag_uppercase,
    ArgFlag_lowercase,
    ArgFlag_titlecase,
    ArgFlag_useGrouping,
    ArgFlag_conditional,
    ArgFlag_quantity,
    ArgFlag_decimalPlaces,
    ArgFlag_leadingZeroes
  };
  return values;
}

inline const char *EnumNameArgFlag(ArgFlag e) {
  switch (e) {
    case ArgFlag_linkify: return "linkify";
    case ArgFlag_capitalize: return "capitalize";
    case ArgFlag_uppercase: return "uppercase";
    case ArgFlag_lowercase: return "lowercase";
    case ArgFlag_titlecase: return "titlecase";
    case ArgFlag_useGrouping: return "useGrouping";
    case ArgFlag_conditional: return "conditional";
    case ArgFlag_quantity: return "quantity";
    case ArgFlag_decimalPlaces: return "decimalPlaces";
    case ArgFlag_leadingZeroes: return "leadingZeroes";
    default: return "";
  }
}

struct Metadata FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MetadataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PROPERTY_NAME = 4,
    VT_TEXT = 6
  };
  const ::flatbuffers::String *property_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PROPERTY_NAME);
  }
  const ::flatbuffers::String *text() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TEXT);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_PROPERTY_NAME) &&
           verifier.VerifyString(property_name()) &&
           VerifyOffset(verifier, VT_TEXT) &&
           verifier.VerifyString(text()) &&
           verifier.EndTable();
  }
};

struct MetadataBuilder {
  typedef Metadata Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_property_name(::flatbuffers::Offset<::flatbuffers::String> property_name) {
    fbb_.AddOffset(Metadata::VT_PROPERTY_NAME, property_name);
  }
  void add_text(::flatbuffers::Offset<::flatbuffers::String> text) {
    fbb_.AddOffset(Metadata::VT_TEXT, text);
  }
  explicit MetadataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Metadata> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Metadata>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Metadata> CreateMetadata(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> property_name = 0,
    ::flatbuffers::Offset<::flatbuffers::String> text = 0) {
  MetadataBuilder builder_(_fbb);
  builder_.add_text(text);
  builder_.add_property_name(property_name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Metadata> CreateMetadataDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *property_name = nullptr,
    const char *text = nullptr) {
  auto property_name__ = property_name ? _fbb.CreateString(property_name) : 0;
  auto text__ = text ? _fbb.CreateString(text) : 0;
  return eve::localization::CreateMetadata(
      _fbb,
      property_name__,
      text__);
}

struct KwargNumber FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef KwargNumberBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALUE = 4
  };
  uint8_t value() const {
    return GetField<uint8_t>(VT_VALUE, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_VALUE, 1) &&
           verifier.EndTable();
  }
};

struct KwargNumberBuilder {
  typedef KwargNumber Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_value(uint8_t value) {
    fbb_.AddElement<uint8_t>(KwargNumber::VT_VALUE, value, 0);
  }
  explicit KwargNumberBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<KwargNumber> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<KwargNumber>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<KwargNumber> CreateKwargNumber(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t value = 0) {
  KwargNumberBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

struct KwargString FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef KwargStringBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALUE = 4
  };
  const ::flatbuffers::String *value() const {
    return GetPointer<const ::flatbuffers::String *>(VT_VALUE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VALUE) &&
           verifier.VerifyString(value()) &&
           verifier.EndTable();
  }
};

struct KwargStringBuilder {
  typedef KwargString Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_value(::flatbuffers::Offset<::flatbuffers::String> value) {
    fbb_.AddOffset(KwargString::VT_VALUE, value);
  }
  explicit KwargStringBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<KwargString> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<KwargString>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<KwargString> CreateKwargString(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> value = 0) {
  KwargStringBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<KwargString> CreateKwargStringDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *value = nullptr) {
  auto value__ = value ? _fbb.CreateString(value) : 0;
  return eve::localization::CreateKwargString(
      _fbb,
      value__);
}

struct Kwarg FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef KwargBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_KEY = 4,
    VT_VALUE_TYPE = 6,
    VT_VALUE = 8
  };
  const ::flatbuffers::String *key() const {
    return GetPointer<const ::flatbuffers::String *>(VT_KEY);
  }
  eve::localization::KwargValue value_type() const {
    return static_cast<eve::localization::KwargValue>(GetField<uint8_t>(VT_VALUE_TYPE, 0));
  }
  const void *value() const {
    return GetPointer<const void *>(VT_VALUE);
  }
  template<typename T> const T *value_as() const;
  const eve::localization::KwargNumber *value_as_KwargNumber() const {
    return value_type() == eve::localization::KwargValue_KwargNumber ? static_cast<const eve::localization::KwargNumber *>(value()) : nullptr;
  }
  const eve::localization::KwargString *value_as_KwargString() const {
    return value_type() == eve::localization::KwargValue_KwargString ? static_cast<const eve::localization::KwargString *>(value()) : nullptr;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_KEY) &&
           verifier.VerifyString(key()) &&
           VerifyField<uint8_t>(verifier, VT_VALUE_TYPE, 1) &&
           VerifyOffset(verifier, VT_VALUE) &&
           VerifyKwargValue(verifier, value(), value_type()) &&
           verifier.EndTable();
  }
};

template<> inline const eve::localization::KwargNumber *Kwarg::value_as<eve::localization::KwargNumber>() const {
  return value_as_KwargNumber();
}

template<> inline const eve::localization::KwargString *Kwarg::value_as<eve::localization::KwargString>() const {
  return value_as_KwargString();
}

struct KwargBuilder {
  typedef Kwarg Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_key(::flatbuffers::Offset<::flatbuffers::String> key) {
    fbb_.AddOffset(Kwarg::VT_KEY, key);
  }
  void add_value_type(eve::localization::KwargValue value_type) {
    fbb_.AddElement<uint8_t>(Kwarg::VT_VALUE_TYPE, static_cast<uint8_t>(value_type), 0);
  }
  void add_value(::flatbuffers::Offset<void> value) {
    fbb_.AddOffset(Kwarg::VT_VALUE, value);
  }
  explicit KwargBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Kwarg> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Kwarg>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Kwarg> CreateKwarg(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> key = 0,
    eve::localization::KwargValue value_type = eve::localization::KwargValue_NONE,
    ::flatbuffers::Offset<void> value = 0) {
  KwargBuilder builder_(_fbb);
  builder_.add_value(value);
  builder_.add_key(key);
  builder_.add_value_type(value_type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Kwarg> CreateKwargDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *key = nullptr,
    eve::localization::KwargValue value_type = eve::localization::KwargValue_NONE,
    ::flatbuffers::Offset<void> value = 0) {
  auto key__ = key ? _fbb.CreateString(key) : 0;
  return eve::localization::CreateKwarg(
      _fbb,
      key__,
      value_type,
      value);
}

struct Token FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TokenBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MARKUP = 4,
    VT_VARIABLE_TYPE = 6,
    VT_VARIABLE_NAME = 8,
    VT_PROPERTY_NAME = 10,
    VT_ARGS = 12,
    VT_KWARGS = 14,
    VT_CONDITIONAL_VALUES = 16
  };
  const ::flatbuffers::String *markup() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MARKUP);
  }
  eve::localization::VariableTypes variable_type() const {
    return static_cast<eve::localization::VariableTypes>(GetField<int8_t>(VT_VARIABLE_TYPE, 0));
  }
  const ::flatbuffers::String *variable_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_VARIABLE_NAME);
  }
  const ::flatbuffers::String *property_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PROPERTY_NAME);
  }
  uint16_t args() const {
    return GetField<uint16_t>(VT_ARGS, 0);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<eve::localization::Kwarg>> *kwargs() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<eve::localization::Kwarg>> *>(VT_KWARGS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *conditional_values() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_CONDITIONAL_VALUES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_MARKUP) &&
           verifier.VerifyString(markup()) &&
           VerifyField<int8_t>(verifier, VT_VARIABLE_TYPE, 1) &&
           VerifyOffset(verifier, VT_VARIABLE_NAME) &&
           verifier.VerifyString(variable_name()) &&
           VerifyOffset(verifier, VT_PROPERTY_NAME) &&
           verifier.VerifyString(property_name()) &&
           VerifyField<uint16_t>(verifier, VT_ARGS, 2) &&
           VerifyOffset(verifier, VT_KWARGS) &&
           verifier.VerifyVector(kwargs()) &&
           verifier.VerifyVectorOfTables(kwargs()) &&
           VerifyOffset(verifier, VT_CONDITIONAL_VALUES) &&
           verifier.VerifyVector(conditional_values()) &&
           verifier.VerifyVectorOfStrings(conditional_values()) &&
           verifier.EndTable();
  }
};

struct TokenBuilder {
  typedef Token Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_markup(::flatbuffers::Offset<::flatbuffers::String> markup) {
    fbb_.AddOffset(Token::VT_MARKUP, markup);
  }
  void add_variable_type(eve::localization::VariableTypes variable_type) {
    fbb_.AddElement<int8_t>(Token::VT_VARIABLE_TYPE, static_cast<int8_t>(variable_type), 0);
  }
  void add_variable_name(::flatbuffers::Offset<::flatbuffers::String> variable_name) {
    fbb_.AddOffset(Token::VT_VARIABLE_NAME, variable_name);
  }
  void add_property_name(::flatbuffers::Offset<::flatbuffers::String> property_name) {
    fbb_.AddOffset(Token::VT_PROPERTY_NAME, property_name);
  }
  void add_args(uint16_t args) {
    fbb_.AddElement<uint16_t>(Token::VT_ARGS, args, 0);
  }
  void add_kwargs(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<eve::localization::Kwarg>>> kwargs) {
    fbb_.AddOffset(Token::VT_KWARGS, kwargs);
  }
  void add_conditional_values(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> conditional_values) {
    fbb_.AddOffset(Token::VT_CONDITIONAL_VALUES, conditional_values);
  }
  explicit TokenBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Token> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Token>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Token> CreateToken(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> markup = 0,
    eve::localization::VariableTypes variable_type = eve::localization::VariableTypes_character,
    ::flatbuffers::Offset<::flatbuffers::String> variable_name = 0,
    ::flatbuffers::Offset<::flatbuffers::String> property_name = 0,
    uint16_t args = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<eve::localization::Kwarg>>> kwargs = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> conditional_values = 0) {
  TokenBuilder builder_(_fbb);
  builder_.add_conditional_values(conditional_values);
  builder_.add_kwargs(kwargs);
  builder_.add_property_name(property_name);
  builder_.add_variable_name(variable_name);
  builder_.add_markup(markup);
  builder_.add_args(args);
  builder_.add_variable_type(variable_type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Token> CreateTokenDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *markup = nullptr,
    eve::localization::VariableTypes variable_type = eve::localization::VariableTypes_character,
    const char *variable_name = nullptr,
    const char *property_name = nullptr,
    uint16_t args = 0,
    const std::vector<::flatbuffers::Offset<eve::localization::Kwarg>> *kwargs = nullptr,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *conditional_values = nullptr) {
  auto markup__ = markup ? _fbb.CreateString(markup) : 0;
  auto variable_name__ = variable_name ? _fbb.CreateString(variable_name) : 0;
  auto property_name__ = property_name ? _fbb.CreateString(property_name) : 0;
  auto kwargs__ = kwargs ? _fbb.CreateVector<::flatbuffers::Offset<eve::localization::Kwarg>>(*kwargs) : 0;
  auto conditional_values__ = conditional_values ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*conditional_values) : 0;
  return eve::localization::CreateToken(
      _fbb,
      markup__,
      variable_type,
      variable_name__,
      property_name__,
      args,
      kwargs__,
      conditional_values__);
}

struct Message FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MessageBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_TEXT = 6,
    VT_TOKENS = 8,
    VT_METADATA = 10
  };
  uint64_t id() const {
    return GetField<uint64_t>(VT_ID, 0);
  }
  bool KeyCompareLessThan(const Message * const o) const {
    return id() < o->id();
  }
  int KeyCompareWithValue(uint64_t _id) const {
    return static_cast<int>(id() > _id) - static_cast<int>(id() < _id);
  }
  const ::flatbuffers::String *text() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TEXT);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<eve::localization::Token>> *tokens() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<eve::localization::Token>> *>(VT_TOKENS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<eve::localization::Metadata>> *metadata() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<eve::localization::Metadata>> *>(VT_METADATA);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_ID, 8) &&
           VerifyOffset(verifier, VT_TEXT) &&
           verifier.VerifyString(text()) &&
           VerifyOffset(verifier, VT_TOKENS) &&
           verifier.VerifyVector(tokens()) &&
           verifier.VerifyVectorOfTables(tokens()) &&
           VerifyOffset(verifier, VT_METADATA) &&
           verifier.VerifyVector(metadata()) &&
           verifier.VerifyVectorOfTables(metadata()) &&
           verifier.EndTable();
  }
};

struct MessageBuilder {
  typedef Message Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(uint64_t id) {
    fbb_.AddElement<uint64_t>(Message::VT_ID, id, 0);
  }
  void add_text(::flatbuffers::Offset<::flatbuffers::String> text) {
    fbb_.AddOffset(Message::VT_TEXT, text);
  }
  void add_tokens(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<eve::localization::Token>>> tokens) {
    fbb_.AddOffset(Message::VT_TOKENS, tokens);
  }
  void add_metadata(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<eve::localization::Metadata>>> metadata) {
    fbb_.AddOffset(Message::VT_METADATA, metadata);
  }
  explicit MessageBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Message> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Message>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Message> CreateMessage(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> text = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<eve::localization::Token>>> tokens = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<eve::localization::Metadata>>> metadata = 0) {
  MessageBuilder builder_(_fbb);
  builder_.add_id(id);
  builder_.add_metadata(metadata);
  builder_.add_tokens(tokens);
  builder_.add_text(text);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Message> CreateMessageDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t id = 0,
    const char *text = nullptr,
    const std::vector<::flatbuffers::Offset<eve::localization::Token>> *tokens = nullptr,
    const std::vector<::flatbuffers::Offset<eve::localization::Metadata>> *metadata = nullptr) {
  auto text__ = text ? _fbb.CreateString(text) : 0;
  auto tokens__ = tokens ? _fbb.CreateVector<::flatbuffers::Offset<eve::localization::Token>>(*tokens) : 0;
  auto metadata__ = metadata ? _fbb.CreateVector<::flatbuffers::Offset<eve::localization::Metadata>>(*metadata) : 0;
  return eve::localization::CreateMessage(
      _fbb,
      id,
      text__,
      tokens__,
      metadata__);
}

struct AllMessages FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef AllMessagesBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MESSAGES = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<eve::localization::Message>> *messages() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<eve::localization::Message>> *>(VT_MESSAGES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_MESSAGES) &&
           verifier.VerifyVector(messages()) &&
           verifier.VerifyVectorOfTables(messages()) &&
           verifier.EndTable();
  }
};

struct AllMessagesBuilder {
  typedef AllMessages Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_messages(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<eve::localization::Message>>> messages) {
    fbb_.AddOffset(AllMessages::VT_MESSAGES, messages);
  }
  explicit AllMessagesBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<AllMessages> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<AllMessages>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<AllMessages> CreateAllMessages(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<eve::localization::Message>>> messages = 0) {
  AllMessagesBuilder builder_(_fbb);
  builder_.add_messages(messages);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<AllMessages> CreateAllMessagesDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    std::vector<::flatbuffers::Offset<eve::localization::Message>> *messages = nullptr) {
  auto messages__ = messages ? _fbb.CreateVectorOfSortedTables<eve::localization::Message>(messages) : 0;
  return eve::localization::CreateAllMessages(
      _fbb,
      messages__);
}

inline bool VerifyKwargValue(::flatbuffers::Verifier &verifier, const void *obj, KwargValue type) {
  switch (type) {
    case KwargValue_NONE: {
      return true;
    }
    case KwargValue_KwargNumber: {
      auto ptr = reinterpret_cast<const eve::localization::KwargNumber *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case KwargValue_KwargString: {
      auto ptr = reinterpret_cast<const eve::localization::KwargString *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyKwargValueVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyKwargValue(
        verifier,  values->Get(i), types->GetEnum<KwargValue>(i))) {
      return false;
    }
  }
  return true;
}

inline const eve::localization::AllMessages *GetAllMessages(const void *buf) {
  return ::flatbuffers::GetRoot<eve::localization::AllMessages>(buf);
}

inline const eve::localization::AllMessages *GetSizePrefixedAllMessages(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<eve::localization::AllMessages>(buf);
}

inline bool VerifyAllMessagesBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<eve::localization::AllMessages>(nullptr);
}

inline bool VerifySizePrefixedAllMessagesBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<eve::localization::AllMessages>(nullptr);
}

inline void FinishAllMessagesBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<eve::localization::AllMessages> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedAllMessagesBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<eve::localization::AllMessages> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace localization
}  // namespace eve

#endif  // FLATBUFFERS_GENERATED_MESSAGES_EVE_LOCALIZATION_H_
